# Makefile for AUTOSAR ECU1 Project

# Compiler & Flags
CC      := gcc
CFLAGS  := -Wall -Werror -IInc -IConfig  -IEcuAbstraction/CanIf  -IMCAL/Can -IMCAL/Dio -IOS -IRTE -IServices/Com -IServices/PduR -IApp -IEcuAbstraction/IoHwAb

# Project folders
SRC_DIRS := App Config EcuAbstraction/IoHwAb EcuAbstraction/CanIf MCAL/Can MCAL/Dio OS RTE Services/Com Services/PduR

# Gather all source files (.c)
SRCS := $(foreach dir,$(SRC_DIRS),$(wildcard $(dir)/*.c))
SRCS += main.c
# Generate object files in Out/
OBJS := $(patsubst %.c,Out/%.o,$(SRCS))

# Output binary
TARGET := Out/autosar_ecu1

# Default rule
all: prepare $(TARGET)

# Create Out/ structure
prepare:
	mkdir -p Out
	@for dir in $(SRC_DIRS); do mkdir -p Out/$$dir; done

# Linking
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@ -pthread -lrt -g

# Compiling source to objects
Out/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@ -pthread -lrt -g

# Clean build artifacts
clean:
	rm -rf Out

.PHONY: all clean prepare
